# Generated by Django 4.1.5 on 2023-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_icalinks_next_alter_icalinks_prev_icextended'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128)),
                ('success', models.BooleanField(default=False)),
                ('dttm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datasetstats',
            name='agreement',
        ),
        migrations.AddField(
            model_name='datasetstats',
            name='n_annotations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetstats',
            name='n_components_with_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetstats',
            name='n_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetstats',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
