# Generated by Django 4.1.5 on 2023-06-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_celerylog_remove_datasetstats_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetstats',
            name='n_components_with_annotations',
            field=models.IntegerField(default=0),
        ),
    ]
