# Generated by Django 4.1.5 on 2023-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_datasetstats_n_components_with_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerylog',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
