# Generated by Django 4.1.5 on 2023-06-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_celerylog_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryLog',
        ),
    ]
