# Generated by Django 3.1.3 on 2021-11-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0008_annotation_flag_eyes_blinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
