# Generated by Django 3.1.3 on 2021-11-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0010_auto_20211105_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='icacomponent',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ics', to='data_app.subject'),
        ),
    ]
