# Generated by Django 3.1.3 on 2021-11-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0011_icacomponent_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('dataset', 'name')},
        ),
    ]
