# Generated by Django 3.1.3 on 2021-11-06 09:29

from django.db import migrations


def create_subject(apps, schema_editor):

    ICAComponent = apps.get_model('data_app', 'ICAComponent')
    Subject = apps.get_model('data_app', 'Subject')

    ics = ICAComponent.objects.all()

    for ic in ics:
        if ic.subject:
            continue
        if Subject.objects.filter(dataset=ic.dataset, name=ic.subject_name).exists():
            subj = Subject.objects.get(dataset=ic.dataset, name=ic.subject_name)
        else:
            subj = Subject.objects.create(dataset=ic.dataset, name=ic.subject_name)
        ic.subject = subj
        ic.save()


def reverse_code(apps, schema_editor):
    Subject = apps.get_model('data_app', 'Subject')
    Subject.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0013_auto_20211106_0929'),
    ]

    operations = [
        migrations.RunPython(create_subject, reverse_code=reverse_code)
    ]