# Generated by Django 4.1.5 on 2023-06-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0014_auto_20211106_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ch_names',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_npy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='sfreq',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='icacomponent',
            name='data_obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ic', to='data_app.icadata'),
        ),
    ]
