# Generated by Django 4.1.5 on 2023-06-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0015_subject_ch_names_subject_has_npy_subject_sfreq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='n_points',
            field=models.IntegerField(null=True),
        ),
    ]
