# Generated by Django 3.1.3 on 2021-11-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0009_annotation_updated_dt'),
        ('downloads_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasetdownloaditem',
            unique_together={('dataset', 'version')},
        ),
    ]
