# Generated by Django 4.1.5 on 2023-06-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('success', 'success'), ('failed', 'failed')], max_length=128)),
                ('dttm', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
    ]
