# Generated by Django 4.1.5 on 2023-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundtask',
            name='finished',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
