# Generated by Django 4.1.5 on 2023-06-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_app', '0003_rename_finished_backgroundtask_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundtask',
            name='dttm',
        ),
    ]
